server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagement_db
    username: root
    password: joeroot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
